HOST_API_PAGE_1 = {
    '_links': {
        'count': 20,
        'next': 'https://127.0.0.1:8000/api/host/?page=2&format=json',
        'previous': None,
        'self': 'https://127.0.0.1:8000/api/host/?format=json'
    },
    'host': [
         {'_links': {'self': 'https://127.0.0.1:8000/api/host/?format=json'},
          'created_at': '20181108135653',
          'database': {'engine': 'redis',
                       'id': 1,
                       'infra': {'id': 1, 'name': 'infra_name1'},
                       'name': 'db_name1',
                       'project_name': 'fake_project'},
          'disks': [],
          'env_name': 'fake_env',
          'hostname': 'fake_hostname1',
          'id': 1,
          'identifier': 'fake_identifier1',
          'offering': {'cpus': 1, 'memory': 1024, 'type': '1c1024'},
          'os_description': 'SOME FAKE LINUX',
          'project_id': 'fake-u-u-id',
          'region_name': 'brazil',
          'team_name': 'fake team',
          'updated_at': '20181108135653'},
         {'_links': {'self': 'https://127.0.0.1:8000/api/host/?format=json'},
          'created_at': '20181108135653',
          'database': {'engine': 'mongodb',
                       'id': 2,
                       'infra': {'id': 2, 'name': 'infra_name2'},
                       'name': 'db_name2',

                       'project_name': 'fake_project'},
          'disks': [],
          'env_name': 'fake_env',
          'hostname': 'fake_hostname2',
          'id': 2,
          'identifier': 'fake_identifier2',
          'offering': {'cpus': 1, 'memory': 1024, 'type': '1c1024'},
          'os_description': 'SOME FAKE LINUX',
          'project_id': 'fake-u-u-id',
          'region_name': 'brazil',
          'team_name': 'fake team',
          'updated_at': '20181108135653'},
         {'_links': {'self': 'https://127.0.0.1:8000/api/host/?format=json'},
          'created_at': '20181108135653',
          'database': {'engine': 'mysql',
                       'id': 3,
                       'infra': {'id': 3, 'name': 'infra_name3'},
                       'name': 'db_name3',
                       'project_name': 'fake_project'},
          'disks': [],
          'env_name': 'fake_env',
          'hostname': 'fake_hostname3',
          'id': 3,
          'identifier': 'fake_identifier3',
          'offering': {'cpus': 1, 'memory': 1024, 'type': '1c1024'},
          'os_description': 'SOME FAKE LINUX',
          'project_id': 'fake-u-u-id',
          'region_name': 'brazil',
          'team_name': 'fake team',
          'updated_at': '20181108135653'},
         {'_links': {'self': 'https://127.0.0.1:8000/api/host/?format=json'},
          'created_at': '20181108135653',
          'database': {'engine': 'redis',
                       'id': 4,
                       'infra': {'id': 4, 'name': 'infra_name4'},
                       'name': 'db_name4',
                       'project_name': 'fake_project'},
          'disks': [],
          'env_name': 'fake_env',
          'hostname': 'fake_hostname4',
          'id': 4,
          'identifier': 'fake_identifier4',
          'offering': {'cpus': 1, 'memory': 1024, 'type': '1c1024'},
          'os_description': 'SOME FAKE LINUX',
          'project_id': 'fake-u-u-id',
          'region_name': 'brazil',
          'team_name': 'fake team',
          'updated_at': '20181108135653'},
         {'_links': {'self': 'https://127.0.0.1:8000/api/host/?format=json'},
          'created_at': '20181108135653',
          'database': {'engine': 'mongodb',
                       'id': 5,
                       'infra': {'id': 5, 'name': 'infra_name5'},
                       'name': 'db_name5',
                       'project_name': 'fake_project'},
          'disks': [],
          'env_name': 'fake_env',
          'hostname': 'fake_hostname5',
          'id': 5,
          'identifier': 'fake_identifier5',
          'offering': {'cpus': 1, 'memory': 1024, 'type': '1c1024'},
          'os_description': 'SOME FAKE LINUX',
          'project_id': 'fake-u-u-id',
          'region_name': 'brazil',
          'team_name': 'fake team',
          'updated_at': '20181108135653'},
         {'_links': {'self': 'https://127.0.0.1:8000/api/host/?format=json'},
          'created_at': '20181108135653',
          'database': {'engine': 'mysql',
                       'id': 6,
                       'infra': {'id': 6, 'name': 'infra_name6'},
                       'name': 'db_name6',
                       'project_name': 'fake_project'},
          'disks': [],
          'env_name': 'fake_env',
          'hostname': 'fake_hostname6',
          'id': 6,
          'identifier': 'fake_identifier6',
          'offering': {'cpus': 1, 'memory': 1024, 'type': '1c1024'},
          'os_description': 'SOME FAKE LINUX',
          'project_id': 'fake-u-u-id',
          'region_name': 'brazil',
          'team_name': 'fake team',
          'updated_at': '20181108135653'},
         {'_links': {'self': 'https://127.0.0.1:8000/api/host/?format=json'},
          'created_at': '20181108135653',
          'database': {'engine': 'redis',
                       'id': 7,
                       'infra': {'id': 7, 'name': 'infra_name7'},
                       'name': 'db_name7',
                       'project_name': 'fake_project'},
          'disks': [],
          'env_name': 'fake_env',
          'hostname': 'fake_hostname7',
          'id': 7,
          'identifier': 'fake_identifier7',
          'offering': {'cpus': 1, 'memory': 1024, 'type': '1c1024'},
          'os_description': 'SOME FAKE LINUX',
          'project_id': 'fake-u-u-id',
          'region_name': 'brazil',
          'team_name': 'fake team',
          'updated_at': '20181108135653'},
         {'_links': {'self': 'https://127.0.0.1:8000/api/host/?format=json'},
          'created_at': '20181108135653',
          'database': {'engine': 'mongodb',
                       'id': 8,
                       'infra': {'id': 8, 'name': 'infra_name8'},
                       'name': 'db_name8',
                       'project_name': 'fake_project'},
          'disks': [],
          'env_name': 'fake_env',
          'hostname': 'fake_hostname8',
          'id': 8,
          'identifier': 'fake_identifier8',
          'offering': {'cpus': 1, 'memory': 1024, 'type': '1c1024'},
          'os_description': 'SOME FAKE LINUX',
          'project_id': 'fake-u-u-id',
          'region_name': 'brazil',
          'team_name': 'fake team',
          'updated_at': '20181108135653'},
         {'_links': {'self': 'https://127.0.0.1:8000/api/host/?format=json'},
          'created_at': '20181108135653',
          'database': {'engine': 'mysql',
                       'id': 9,
                       'infra': {'id': 9, 'name': 'infra_name9'},
                       'name': 'db_name9',
                       'project_name': 'fake_project'},
          'disks': [],
          'env_name': 'fake_env',
          'hostname': 'fake_hostname9',
          'id': 9,
          'identifier': 'fake_identifier9',
          'offering': {'cpus': 1, 'memory': 1024, 'type': '1c1024'},
          'os_description': 'SOME FAKE LINUX',
          'project_id': 'fake-u-u-id',
          'region_name': 'brazil',
          'team_name': 'fake team',
          'updated_at': '20181108135653'},
         {'_links': {'self': 'https://127.0.0.1:8000/api/host/?format=json'},
          'created_at': '20181108135653',
          'database': {'engine': 'redis',
                       'id': 10,
                       'infra': {'id': 10, 'name': 'infra_name10'},
                       'name': 'db_name10',
                       'project_name': 'fake_project'},
          'disks': [],
          'env_name': 'fake_env',
          'hostname': 'fake_hostname10',
          'id': 10,
          'identifier': 'fake_identifier10',
          'offering': {'cpus': 1, 'memory': 1024, 'type': '1c1024'},
          'os_description': 'SOME FAKE LINUX',
          'project_id': 'fake-u-u-id',
          'region_name': 'brazil',
          'team_name': 'fake team',
          'updated_at': '20181108135653'}]
    }


HOST_API_PAGE_2 = {
    '_links': {
        'count': 20,
        'next': None,
        'previous': 'https://127.0.0.1:8000/api/host/?page=1&format=json',
        'self': 'https://127.0.0.1:8000/api/host/?format=json&page=2'
    },
    'host': [
         {'_links': {'self': 'https://127.0.0.1:8000/api/host/?format=json'},
          'created_at': '20181108135719',
          'database': {'engine': 'mongodb',
                       'id': 11,
                       'infra': {'id': 11, 'name': 'infra_name11'},
                       'name': 'db_name11',
                       'project_name': 'fake_project'},
          'disks': [],
          'env_name': 'fake_env',
          'hostname': 'fake_hostname11',
          'id': 11,
          'identifier': 'fake_identifier11',
          'offering': {'cpus': 1, 'memory': 1024, 'type': '1c1024'},
          'os_description': 'SOME FAKE LINUX',
          'project_id': 'fake-u-u-id',
          'region_name': 'brazil',
          'team_name': 'fake team',
          'updated_at': '20181108135719'},
         {'_links': {'self': 'https://127.0.0.1:8000/api/host/?format=json'},
          'created_at': '20181108135719',
          'database': {'engine': 'mysql',
                       'id': 12,
                       'infra': {'id': 12, 'name': 'infra_name12'},
                       'name': 'db_name12',
                       'project_name': 'fake_project'},
          'disks': [],
          'env_name': 'fake_env',
          'hostname': 'fake_hostname12',
          'id': 12,
          'identifier': 'fake_identifier12',
          'offering': {'cpus': 1, 'memory': 1024, 'type': '1c1024'},
          'os_description': 'SOME FAKE LINUX',
          'project_id': 'fake-u-u-id',
          'region_name': 'brazil',
          'team_name': 'fake team',
          'updated_at': '20181108135719'},
         {'_links': {'self': 'https://127.0.0.1:8000/api/host/?format=json'},
          'created_at': '20181108135719',
          'database': {'engine': 'redis',
                       'id': 13,
                       'infra': {'id': 13, 'name': 'infra_name13'},
                       'name': 'db_name13',
                       'project_name': 'fake_project'},
          'disks': [],
          'env_name': 'fake_env',
          'hostname': 'fake_hostname13',
          'id': 13,
          'identifier': 'fake_identifier13',
          'offering': {'cpus': 1, 'memory': 1024, 'type': '1c1024'},
          'os_description': 'SOME FAKE LINUX',
          'project_id': 'fake-u-u-id',
          'region_name': 'brazil',
          'team_name': 'fake team',
          'updated_at': '20181108135719'},
         {'_links': {'self': 'https://127.0.0.1:8000/api/host/?format=json'},
          'created_at': '20181108135719',
          'database': {'engine': 'mongodb',
                       'id': 14,
                       'infra': {'id': 14, 'name': 'infra_name14'},
                       'name': 'db_name14',
                       'project_name': 'fake_project'},
          'disks': [],
          'env_name': 'fake_env',
          'hostname': 'fake_hostname14',
          'id': 14,
          'identifier': 'fake_identifier14',
          'offering': {'cpus': 1, 'memory': 1024, 'type': '1c1024'},
          'os_description': 'SOME FAKE LINUX',
          'project_id': 'fake-u-u-id',
          'region_name': 'brazil',
          'team_name': 'fake team',
          'updated_at': '20181108135719'},
         {'_links': {'self': 'https://127.0.0.1:8000/api/host/?format=json'},
          'created_at': '20181108135719',
          'database': {'engine': 'mysql',
                       'id': 15,
                       'infra': {'id': 15, 'name': 'infra_name15'},
                       'name': 'db_name15',
                       'project_name': 'fake_project'},
          'disks': [],
          'env_name': 'fake_env',
          'hostname': 'fake_hostname15',
          'id': 15,
          'identifier': 'fake_identifier15',
          'offering': {'cpus': 1, 'memory': 1024, 'type': '1c1024'},
          'os_description': 'SOME FAKE LINUX',
          'project_id': 'fake-u-u-id',
          'region_name': 'brazil',
          'team_name': 'fake team',
          'updated_at': '20181108135719'},
         {'_links': {'self': 'https://127.0.0.1:8000/api/host/?format=json'},
          'created_at': '20181108135719',
          'database': {'engine': 'redis',
                       'id': 16,
                       'infra': {'id': 16, 'name': 'infra_name16'},
                       'name': 'db_name16',
                       'project_name': 'fake_project'},
          'disks': [],
          'env_name': 'fake_env',
          'hostname': 'fake_hostname16',
          'id': 16,
          'identifier': 'fake_identifier16',
          'offering': {'cpus': 1, 'memory': 1024, 'type': '1c1024'},
          'os_description': 'SOME FAKE LINUX',
          'project_id': 'fake-u-u-id',
          'region_name': 'brazil',
          'team_name': 'fake team',
          'updated_at': '20181108135719'},
         {'_links': {'self': 'https://127.0.0.1:8000/api/host/?format=json'},
          'created_at': '20181108135719',
          'database': {'engine': 'mongodb',
                       'id': 17,
                       'infra': {'id': 17, 'name': 'infra_name17'},
                       'name': 'db_name17',
                       'project_name': 'fake_project'},
          'disks': [],
          'env_name': 'fake_env',
          'hostname': 'fake_hostname17',
          'id': 17,
          'identifier': 'fake_identifier17',
          'offering': {'cpus': 1, 'memory': 1024, 'type': '1c1024'},
          'os_description': 'SOME FAKE LINUX',
          'project_id': 'fake-u-u-id',
          'region_name': 'brazil',
          'team_name': 'fake team',
          'updated_at': '20181108135719'},
         {'_links': {'self': 'https://127.0.0.1:8000/api/host/?format=json'},
          'created_at': '20181108135719',
          'database': {'engine': 'mysql',
                       'id': 18,
                       'infra': {'id': 18, 'name': 'infra_name18'},
                       'name': 'db_name18',
                       'project_name': 'fake_project'},
          'disks': [],
          'env_name': 'fake_env',
          'hostname': 'fake_hostname18',
          'id': 18,
          'identifier': 'fake_identifier18',
          'offering': {'cpus': 1, 'memory': 1024, 'type': '1c1024'},
          'os_description': 'SOME FAKE LINUX',
          'project_id': 'fake-u-u-id',
          'region_name': 'brazil',
          'team_name': 'fake team',
          'updated_at': '20181108135719'},
         {'_links': {'self': 'https://127.0.0.1:8000/api/host/?format=json'},
          'created_at': '20181108135719',
          'database': {'engine': 'redis',
                       'id': 19,
                       'infra': {'id': 19, 'name': 'infra_name19'},
                       'name': 'db_name19',
                       'project_name': 'fake_project'},
          'disks': [],
          'env_name': 'fake_env',
          'hostname': 'fake_hostname19',
          'id': 19,
          'identifier': 'fake_identifier19',
          'offering': {'cpus': 1, 'memory': 1024, 'type': '1c1024'},
          'os_description': 'SOME FAKE LINUX',
          'project_id': 'fake-u-u-id',
          'region_name': 'brazil',
          'team_name': 'fake team',
          'updated_at': '20181108135719'},
         {'_links': {'self': 'https://127.0.0.1:8000/api/host/?format=json'},
          'created_at': '20181108135719',
          'database': {'engine': 'mongodb',
                       'id': 20,
                       'infra': {'id': 20, 'name': 'infra_name20'},
                       'name': 'db_name20',
                       'project_name': 'fake_project'},
          'disks': [],
          'env_name': 'fake_env',
          'hostname': 'fake_hostname20',
          'id': 20,
          'identifier': 'fake_identifier20',
          'offering': {'cpus': 1, 'memory': 1024, 'type': '1c1024'},
          'os_description': 'SOME FAKE LINUX',
          'project_id': 'fake-u-u-id',
          'region_name': 'brazil',
          'team_name': 'fake team',
          'updated_at': '20181108135719'
          }]
}
