from os import getenv


DATABASE_PROVIDER = getenv("DATABASE_PROVIDER", "bento")
MAP_PROVIDER = getenv("MAP_PROVIDER", "map")

DATABASE_COLLECTION = getenv("DATABASE_COLLECTION", "db")
DB_HOST_COLLECTION = getenv("DB_HOST_COLLECTION", "vm_db")
HOST_COLLECTION = getenv("HOST_COLLECTION", "vm")
DB_TSURU_COLLECTION = getenv("DB_TSURU_COLLECTION", "tsuru-bento")
TSURU_SERVICE_COLLECTION = getenv(
    "TSURU_SERVICE_COLLECTION", "tsuru_service_instance"
)
TSURU_PRODUCTION_ENVIRONMENT = getenv("TSURU_PRODUCTION_ENVIRONMENT", "prod")
TSURU_SERIVCE_BASE_NAME = getenv("TSURU_SERIVCE_BASE_NAME", "tsuru_tsuru-bento")
BENTO_ENDPOINT = getenv("BENTO_ENDPOINT", '127.0.0.1:8000')

MAP_ENDPOINT = getenv("MAP_ENDPOINT", "127.0.0.1:5000")
MAP_USERNAME = getenv("MAP_USERNAME")
MAP_PASSWORD = getenv("MAP_PASSWORD")

BOT_ENDPOINT = getenv("BOT_ENDPOINT", "127.0.0.1:5001")

HOST_PROVIDER_ENDPOINT = getenv("HOST_PROVIDER_ENDPOINT", "127.0.0.1:5002")
HOST_PROVIDER_USER = getenv("HOST_PROVIDER_USER", None)
HOST_PROVIDER_PASSWORD = getenv("HOST_PROVIDER_PASSWORD", None)
